### ISSUE TITLE
merge dawn changes to cdt/org.eclipse.launchbar

### ISSUE THREAD

**Issue by belkassaby** [Itema-as/org.eclipse.launchbar#6]
Hi Torkild, would it make sense to try to merge the Dawn changes to the original cdt launchbar? if so we could submit a new ticket on Eclipse. 
I hope everything is doing fine for you. cheers

**Comment by belkassaby** [comment]
Or, could we update this repository with the latest changes on the cdt/org.eclipse.launchar one?

**Comment by turesheim** [comment]
Hi Baha, I think the latter would be a good option to start with. In any case we would have to rebase against the current official launchbar before merging.

**Comment by belkassaby** [comment]
here is the PR for the changes on master: https://github.com/Itema-as/org.eclipse.launchbar/pull/7

**Comment by belkassaby** [comment]
great thanks! closing this issue.
